name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: project1-repo-development-ecr
  ECS_SERVICE: project1-repo-development-ecs-service
  ECS_CLUSTER: project1-repo-development-cluster
  ECS_TASK_DEFINITION: project1-repo-development-task-definition
  CONTAINER_NAME: project1-repo-development-container

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::828411126532:role/github-actions-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: build and tag docker image
        run: |
          IMAGE_TAG=build-${GITHUB_RUN_NUMBER}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          docker build -t ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker tag ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: push docker image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          echo "image=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Terraform Init/Plan/Apply
      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ./Terraform

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan -var="image_tag=${{ env.IMAGE_TAG }}"
        working-directory: ./Terraform

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
        working-directory: ./Terraform

      - name: Debug OIDC token
        run: |
          echo "${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" | \
          jq -R 'split(".") | .[1] | @base64d | fromjson'
        env:
         ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ steps.configure-aws-credentials.outputs.id-token }}